# Generated by Django 4.2 on 2024-02-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprs', '0008_ipr_start_date_alter_ipr_end_date_alter_ipr_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Failed', 'Просрочен'), ('No status', 'Без статуса'), ('In progress', 'В работе'), ('Done', 'Выполнен'), ('Canceled', 'Отменен')], default='No status', max_length=20, verbose_name='Статус'),
        ),
    ]
